### ISSUE TITLE
Audio muffler settings do not persist

### ISSUE THREAD

**Issue by rocket-girl-e** [ensou04/RocketSoundEnhancement#25]
Particularly referring to the main muffler slider - I set it to 100% for full quietness in vacuum, but after any scene change (reloading, switching to another vessel, switching to KSC etc...) it resets to its default 81% setting. Also, staging sound is always present, even if I select it to be disabled and even when muffling works. 

List of mods below. 
[Modlist (loader info).txt](https://github.com/ensou04/RocketSoundEnhancement/files/12022882/Modlist.loader.info.txt)

**Comment by JonnyOThan** [comment]
No repro.  I changed the muffler setting, clicked save, switched vessels, and the muffler setting was still where I set it.

If this is still occurring I need log files and detailed repro steps.
