### ISSUE TITLE
Sound Effect stops when another mod's Engine Ignites, in M1 Mac

### ISSUE THREAD

**Issue by halver3214** [ensou04/RocketSoundEnhancement#8]
Thank you for your awesome work! And sorry for my poor English.
I use your mod with another Engine Mod(ex. Cryogenic Engines).
In Windows 10 Pro(20H2), RocketSoundEnhancement(RSE) runs in normal. Even if with Cryo Mod, or another Engine mod.
But MacOS 12.1 on M1 Mac(2021) with ARM64 architecture,
when I launch some vehicle with Cryo Mod Engine, from launchpad, noisy sound hit my ears for some second, and all of KSP's SE cut off. In ascending, drop used stage(with Cryo Engine), and vanilla Engine ignite, KSP's SE came back.
Is this problem cause by your mods? or by another mods?

I cannot recognize this probrem causes from, so I wrote here...

Can I help for you for resolve this issue?

KSP and all mod's version is latest.(in 2022/02/10)

Thank you.

**Comment by ensou04** [comment]
It's probably a compile error. Unfortunately I can't test this because I only have a Windows PC.

**Comment by halver3214** [comment]
Thank you for your replying!

**Comment by ensou04** [comment]
This bug is potentially solved on v0.6.x. Can you confirm this for me? @halver3214

**Comment by halver3214** [comment]
> This bug is potentially solved on v0.6.x. Can you confirm this for me? @halver3214 

Thank you for your work!
I'll try it so wait please!
